CREATE TABLE LANGCOURSE
(
    ID int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NAME varchar(50),
    LANGUAGE varchar(50),
    PRICE DOUBLE
);

CREATE TABLE TOPIC
(
    ID int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NAME varchar(50),
    DESCRIPTION varchar(50),
    COURSEID int,
    CONSTRAINT TOPIC_LANGCOURSE_ID_FK FOREIGN KEY (COURSEID) REFERENCES LANGCOURSE (ID)
);

CREATE TABLE TEST
(
    ID int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NAME varchar(50),
    TOPICID int,
    CONSTRAINT TEST_TOPIC_ID_FK FOREIGN KEY (TOPICID) REFERENCES TOPIC (ID)
);

CREATE TABLE QUESTION
(
    ID int PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    QUESTIONTEXT varchar(100),
    ANSWERS BLOB,
    RIGHTANSWERS BLOB,
    TESTID int,
    CONSTRAINT QUESTION_TEST_ID_FK FOREIGN KEY (TESTID) REFERENCES TEST (ID)
);

INSERT INTO LANGCOURSE (NAME, LANGUAGE, PRICE) VALUES ('English A1', 'English', 189.9);
INSERT INTO LANGCOURSE (NAME, LANGUAGE, PRICE) VALUES ('English A2', 'English', 123.6);

INSERT INTO TOPIC (NAME, DESCRIPTION, COURSEID) VALUES ('2nd Chapter', 'Written language', 1);

INSERT INTO TEST (NAME, TOPICID) VALUES ('Basic test', 1);